lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 3024000
    token_extractors:
        # look for a token as Authorization Header
        authorization_header:
            enabled: true
            prefix:  sitok
            name:    Authorization

        # check token in a cookie
        cookie:
            enabled: false
            name:    sitok
            
        # check token in query string parameter
        query_parameter:
            enabled: true
            name:    sitok